settings:
  title: 'Status Page'
  url: 'https://status.monbox.kr' # used for Slack messages
  logo: img1.daumcdn.net.jpg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: monbox-kr # unique identifier
    name: monbox.kr
    description: 'MonBox Main Page' # default=empty
    url: 'https://monbox.kr/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    
  - id: blog-monbox-kr # unique identifier
    name: blog.monbox.kr (Tistory)
    description: 'MonBox Blog Page (Powered by Tistory)' # default=empty
    url: 'https://blog.monbox.kr/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    
  - id: private-server # unique identifier
    name: Private Server
    description: 'MonBox Private Page' # default=empty
    url: ${{ secrets.PRIVATE_SERVER_URL }} # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: false # should the titles be links to the service, default=true
    
    
